//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int AutoCounter { get; set; }
        public int VariableID { get; set; }
        public double DataValue { get; set; }
        public string CategoryDescription { get; set; }
    
        public virtual Variable Variable { get; set; }
    }
}
