//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataValue
    {
        public DataValue()
        {
            this.DerivedFroms = new HashSet<DerivedFrom>();
            this.Groups = new HashSet<Group>();
        }
    
        public int ValueID { get; set; }
        public double DataValue1 { get; set; }
        public Nullable<double> ValueAccuracy { get; set; }
        public System.DateTime LocalDateTime { get; set; }
        public double UTCOffset { get; set; }
        public System.DateTime DateTimeUTC { get; set; }
        public int SiteID { get; set; }
        public int VariableID { get; set; }
        public Nullable<double> OffsetValue { get; set; }
        public Nullable<int> OffsetTypeID { get; set; }
        public string CensorCode { get; set; }
        public Nullable<int> QualifierID { get; set; }
        public int MethodID { get; set; }
        public int SourceID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<int> DerivedFromID { get; set; }
        public int QualityControlLevelID { get; set; }
    
        public virtual CensorCodeCV CensorCodeCV { get; set; }
        public virtual Method Method { get; set; }
        public virtual OffsetType OffsetType { get; set; }
        public virtual Qualifier Qualifier { get; set; }
        public virtual QualityControlLevel QualityControlLevel { get; set; }
        public virtual Sample Sample { get; set; }
        public virtual Site Site { get; set; }
        public virtual Source Source { get; set; }
        public virtual Variable Variable { get; set; }
        public virtual ICollection<DerivedFrom> DerivedFroms { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
