//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int GroupID { get; set; }
        public int ValueID { get; set; }
        public int AutoCounter { get; set; }
    
        public virtual DataValue DataValue { get; set; }
        public virtual GroupDescription GroupDescription { get; set; }
    }
}
