//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDescription
    {
        public GroupDescription()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int GroupID { get; set; }
        public string GroupDescription1 { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
    }
}
