//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabMethod
    {
        public LabMethod()
        {
            this.Samples = new HashSet<Sample>();
        }
    
        public int LabMethodID { get; set; }
        public string LabName { get; set; }
        public string LabOrganization { get; set; }
        public string LabMethodName { get; set; }
        public string LabMethodDescription { get; set; }
        public string LabMethodLink { get; set; }
    
        public virtual ICollection<Sample> Samples { get; set; }
    }
}
