//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODM_1_1_1Entities : DbContext
    {
        public ODM_1_1_1Entities()
            : base("name=ODM_1_1_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CensorCodeCV> CensorCodeCVs { get; set; }
        public virtual DbSet<DataTypeCV> DataTypeCVs { get; set; }
        public virtual DbSet<DataValue> DataValues { get; set; }
        public virtual DbSet<DerivedFrom> DerivedFroms { get; set; }
        public virtual DbSet<GeneralCategoryCV> GeneralCategoryCVs { get; set; }
        public virtual DbSet<GroupDescription> GroupDescriptions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<ISOMetadata> ISOMetadatas { get; set; }
        public virtual DbSet<LabMethod> LabMethods { get; set; }
        public virtual DbSet<Method> Methods { get; set; }
        public virtual DbSet<ODMVersion> ODMVersions { get; set; }
        public virtual DbSet<OffsetType> OffsetTypes { get; set; }
        public virtual DbSet<Qualifier> Qualifiers { get; set; }
        public virtual DbSet<QualityControlLevel> QualityControlLevels { get; set; }
        public virtual DbSet<SampleMediumCV> SampleMediumCVs { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<SampleTypeCV> SampleTypeCVs { get; set; }
        public virtual DbSet<SeriesCatalog> SeriesCatalogs { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteTypeCV> SiteTypeCVs { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<SpatialReference> SpatialReferences { get; set; }
        public virtual DbSet<SpeciationCV> SpeciationCVs { get; set; }
        public virtual DbSet<TopicCategoryCV> TopicCategoryCVs { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<ValueTypeCV> ValueTypeCVs { get; set; }
        public virtual DbSet<VariableNameCV> VariableNameCVs { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<VerticalDatumCV> VerticalDatumCVs { get; set; }
    }
}
