//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControlLevel
    {
        public QualityControlLevel()
        {
            this.DataValues = new HashSet<DataValue>();
        }
    
        public int QualityControlLevelID { get; set; }
        public string QualityControlLevelCode { get; set; }
        public string Definition { get; set; }
        public string Explanation { get; set; }
    
        public virtual ICollection<DataValue> DataValues { get; set; }
    }
}
