//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public Sample()
        {
            this.DataValues = new HashSet<DataValue>();
        }
    
        public int SampleID { get; set; }
        public string SampleType { get; set; }
        public string LabSampleCode { get; set; }
        public int LabMethodID { get; set; }
    
        public virtual ICollection<DataValue> DataValues { get; set; }
        public virtual LabMethod LabMethod { get; set; }
        public virtual SampleTypeCV SampleTypeCV { get; set; }
    }
}
