//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesCatalog
    {
        public int SeriesID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public string SiteType { get; set; }
        public Nullable<int> VariableID { get; set; }
        public string VariableCode { get; set; }
        public string VariableName { get; set; }
        public string Speciation { get; set; }
        public Nullable<int> VariableUnitsID { get; set; }
        public string VariableUnitsName { get; set; }
        public string SampleMedium { get; set; }
        public string ValueType { get; set; }
        public Nullable<double> TimeSupport { get; set; }
        public Nullable<int> TimeUnitsID { get; set; }
        public string TimeUnitsName { get; set; }
        public string DataType { get; set; }
        public string GeneralCategory { get; set; }
        public Nullable<int> MethodID { get; set; }
        public string MethodDescription { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string Organization { get; set; }
        public string SourceDescription { get; set; }
        public string Citation { get; set; }
        public Nullable<int> QualityControlLevelID { get; set; }
        public string QualityControlLevelCode { get; set; }
        public Nullable<System.DateTime> BeginDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> BeginDateTimeUTC { get; set; }
        public Nullable<System.DateTime> EndDateTimeUTC { get; set; }
        public Nullable<int> ValueCount { get; set; }
    }
}
