//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeciationCV
    {
        public SpeciationCV()
        {
            this.Variables = new HashSet<Variable>();
        }
    
        public string Term { get; set; }
        public string Definition { get; set; }
    
        public virtual ICollection<Variable> Variables { get; set; }
    }
}
