//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.OffsetTypes = new HashSet<OffsetType>();
            this.Variables = new HashSet<Variable>();
            this.Variables1 = new HashSet<Variable>();
        }
    
        public int UnitsID { get; set; }
        public string UnitsName { get; set; }
        public string UnitsType { get; set; }
        public string UnitsAbbreviation { get; set; }
    
        public virtual ICollection<OffsetType> OffsetTypes { get; set; }
        public virtual ICollection<Variable> Variables { get; set; }
        public virtual ICollection<Variable> Variables1 { get; set; }
    }
}
