//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODM_1_1_1EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public Variable()
        {
            this.Categories = new HashSet<Category>();
            this.DataValues = new HashSet<DataValue>();
        }
    
        public int VariableID { get; set; }
        public string VariableCode { get; set; }
        public string VariableName { get; set; }
        public string Speciation { get; set; }
        public int VariableUnitsID { get; set; }
        public string SampleMedium { get; set; }
        public string ValueType { get; set; }
        public bool IsRegular { get; set; }
        public double TimeSupport { get; set; }
        public int TimeUnitsID { get; set; }
        public string DataType { get; set; }
        public string GeneralCategory { get; set; }
        public double NoDataValue { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual DataTypeCV DataTypeCV { get; set; }
        public virtual ICollection<DataValue> DataValues { get; set; }
        public virtual GeneralCategoryCV GeneralCategoryCV { get; set; }
        public virtual SampleMediumCV SampleMediumCV { get; set; }
        public virtual SpeciationCV SpeciationCV { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual ValueTypeCV ValueTypeCV { get; set; }
        public virtual VariableNameCV VariableNameCV { get; set; }
    }
}
